// Browser checks for accounts and saved sessions. Run: npm test (needs Playwright's Chromium).
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { createServer } = require('./server.cjs');
// The 5-minute run is generated by the server (this same process): remember its current question to answer it.
const { suspicious } = require('../api/ninja.js');
let srvQ = null;
for (const G of [Figures, Numeric, English]) for (const k of Object.keys(G.make)) { const f = G.make[k]; G.make[k] = (d, u) => (srvQ = f(d, u)); }
const SITE = 'http://127.0.0.1:4191';
const check = (name, ok) => { assert.ok(ok, name); console.log('PASS', name); };

async function typeLesson(page) {
  const text = await page.evaluate(() => [...document.querySelectorAll('#inner .c')].map(s => s.textContent).join(''));
  for (const ch of text) await page.keyboard.press(ch === ' ' ? 'Space' : ch);
}
// Long texts with accents and capitals: send the key events straight to the page.
function typeText(page) {
  return page.evaluate(() => {
    const text = [...document.querySelectorAll('#inner .c')].map(s => s.textContent).join('');
    for (const key of text) document.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true }));
  });
}

(async () => {
  const server = createServer(); await new Promise(r => server.listen(4191, '127.0.0.1', r));
  const browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
  const errors = [];
  try {
    // First computer: create an account and practice
    const a = await browser.newPage(); a.on('pageerror', e => errors.push(e.message));
    const authCalls = []; a.on('request', r => r.url().endsWith('/api/auth') && authCalls.push(r.method()));
    await a.goto(SITE); await a.waitForLoadState('networkidle');
    check('A guest without a session does not ask the server for one', authCalls.length === 0);
    check('Page IDs are unique', await a.evaluate(() => {
      const ids = [...document.querySelectorAll('[id]')].map(el => el.id);
      return new Set(ids).size === ids.length;
    }));
    await a.click('.scene-picker [data-scene="mountains"]');
    await a.reload();
    check('Landscape choice survives a reload', await a.getAttribute('html', 'data-scene') === 'mountains'
      && await a.getAttribute('.scene-picker [data-scene="mountains"]', 'aria-pressed') === 'true');
    for (const scene of ['beach', 'mountains', 'forest']) {
      const asset = await a.request.get(SITE + '/assets/' + scene + '.jpg');
      check('Landscape asset loads: ' + scene, asset.ok() && asset.headers()['content-type'] === 'image/jpeg');
    }
    check('The hero has the three landscapes and no drawings on them', await a.locator('.hero-slides .slide').count() === 3 && await a.locator('.hero-slides svg').count() === 0);
    const firstScene = await a.getAttribute('html', 'data-hero-scene');
    await a.waitForFunction(s => document.documentElement.dataset.heroScene !== s, firstScene, { timeout: 10000 });
    check('The hero changes landscape by itself', await a.locator('.hero-slides .slide.on').count() === 1);
    const levels = await a.$$eval('#learning .evo-card b', els => els.map(e => e.textContent));
    check('Each group is its own level, with the final one at the end', levels.join() === 'Nivel chimpancé,Nivel bebé,Nivel niño,Nivel ninja del mate,Nivel intelectual,Nivel premio Nobel');
    check('Each level shows its own typist', new Set(await a.$$eval('#learning .evo-card svg', els => els.map(e => e.innerHTML))).size === 6);
    check('Levels not started look locked', await a.locator('#learning .evo-art.locked').count() === 6);
    await a.click('#continue');
    await a.locator('.scene-picker [data-scene="forest"]').press('Space');
    check('Changing the landscape by keyboard does not type into the exercise',
      await a.getAttribute('html', 'data-scene') === 'forest' && await a.locator('#inner .c.ok, #inner .c.bad').count() === 0);
    await a.click('.main-nav a[href="#learning"]');
    check('Lesson navigation returns home', await a.isVisible('#home') && await a.isHidden('#lesson'));
    check('Guests see the login button', (await a.textContent('#acctBtn')).trim() === 'Entrar');
    check('The home has a general hero, a big card per section and the rankings before the sections', await a.evaluate(() => {
      const order = ['heroTitle', 'sections', 'ranking', 'teclado', 'cog'].map(id => document.getElementById(id));
      return order.every((el, i) => !i || order[i - 1].compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING);
    }) && (await a.textContent('#heroTitle')).includes('Desarrollá tus habilidades') && await a.locator('.sc-card').count() === 2);
    check('The ranking has a general board and one per section', (await a.textContent('#rankView')).includes('General') && await a.locator('#rankView button').count() === 5);
    check('With META_PIXEL_ID=off the Meta Pixel is not loaded', !(await a.evaluate(() => 'fbq' in window)) && !(await a.evaluate(() => [...document.scripts].some(x => x.src.includes('facebook')))));
    check('The app is called Templo Ninja', (await a.title()) === 'Templo Ninja' && (await a.textContent('#homeBtn')).includes('Templo Ninja'));
    check('The header shows both sections right after the brand', await a.evaluate(() => document.getElementById('homeBtn').nextElementSibling.id === 'tcCta' && document.getElementById('tcCta').nextElementSibling.id === 'cogCta') && (await a.textContent('#tcCta')).includes('Teclado Ciego') && (await a.textContent('#cogCta')).includes('Ninja mental'));
    check('The upgrade CTA sits left of the login, also for guests', await a.isVisible('#upgradeCta') && await a.evaluate(() => document.getElementById('upgradeCta').nextElementSibling.id === 'acctBtn'));
    await a.click('#upgradeCta');
    check('Without payments the upgrade CTA explains the plan is coming', await a.isVisible('#planDlg') && (await a.textContent('#planReason')).includes('en camino') && await a.isHidden('#planSubmit'));
    await a.click('#planClose');
    await a.click('#acctBtn'); await a.click('#authMode [data-v="register"]');
    await a.fill('#user', 'ab'); await a.fill('#pass', 'secreto1'); await a.click('#authSubmit');
    await a.waitForFunction(() => document.querySelector('#authErr').textContent);
    check('Short usernames are rejected', (await a.textContent('#authErr')).includes('entre 3 y 20'));
    await a.fill('#user', 'Ana'); await a.click('#authSubmit');
    await a.waitForSelector('#acctBtn .nm');
    check('Registering signs in', (await a.textContent('#acctBtn .nm')) === 'ana');
    await a.click('#continue'); await typeLesson(a);
    await a.waitForSelector('#result:not([hidden])');
    check('The lesson result shows the level progress', (await a.textContent('.result-evo')).includes('1 de 6 lecciones'));
    await a.waitForTimeout(300);
    await a.click('#rHome');
    check('The started level is no longer locked', await a.getAttribute('#learning .evo-card >> nth=0', 'data-done') === '1' && await a.locator('#learning .evo-art.locked').count() === 5);

    // On-screen keyboards (Android reports keys as "Unidentified"): text arrives only as input
    await a.click('.lc >> nth=19');
    const input = async (value, composing) => a.evaluate(([v, c]) => {
      const cap = document.getElementById('cap'); cap.value = v;
      cap.dispatchEvent(new InputEvent('input', { data: v, isComposing: c, bubbles: true }));
    }, [value, composing]);
    await input('á', false);
    check('Typing into the field without key events works', (await a.locator('#inner .c.ok').count()) === 1);
    // Dead key on a Mac: "´" then "é" as one composition
    await input(' ', false);
    await input('´', true);
    check('A pending accent mark is not counted as an error', (await a.locator('#inner .c.bad').count()) === 0);
    await input('é', true);
    await a.evaluate(() => document.getElementById('cap').dispatchEvent(new CompositionEvent('compositionend', { data: 'é' })));
    check('The composed accent is accepted once', (await a.locator('#inner .c.ok').count()) === 3 && (await a.inputValue('#cap')) === '');
    // Safari on a Mac: the composition ends with the mark alone, the accented vowel comes after
    await input(' ', false);
    await input('´', true);
    await a.evaluate(() => document.getElementById('cap').dispatchEvent(new CompositionEvent('compositionend', { data: '´' })));
    check('Safari: a lonely accent mark waits for its vowel', (await a.locator('#inner .c.bad').count()) === 0 && (await a.inputValue('#cap')) === '´');
    await input('í', false);
    check('Safari: the accented vowel arrives after and counts', (await a.locator('#inner .c.ok').count()) === 5 && (await a.inputValue('#cap')) === '');
    // Mark and vowel as two separate characters
    await input(' ´o', false);
    check('A mark followed by its vowel becomes the accented vowel', (await a.locator('#inner .c.ok').count()) === 7 && (await a.locator('#inner .c.bad').count()) === 0);
    // Dead key while the typing field is not focused (after clicking elsewhere)
    await a.evaluate(() => document.getElementById('cap').blur());
    const key = (k, extra = {}) => a.evaluate(([k, x]) => document.body.dispatchEvent(new KeyboardEvent('keydown', { key: k, bubbles: true, cancelable: true, ...x })), [k, extra]);
    await key(' '); await key('Dead', { code: 'BracketLeft' }); await key('u');
    check('A dead key outside the field still puts the accent', (await a.locator('#inner .c.ok').count()) === 9 && (await a.locator('#inner .c.bad').count()) === 0);
    // Mac press-and-hold menu: the plain vowel first, then the accented one replaces it
    const typeToAccent = () => a.evaluate(() => {
      const spans = [...document.querySelectorAll('#inner .c')];
      for (let i = spans.findIndex(s => s.classList.contains('cur')); i < spans.length && !'áéíóú'.includes(spans[i].textContent); i++)
        document.dispatchEvent(new KeyboardEvent('keydown', { key: spans[i].textContent, bubbles: true, cancelable: true }));
      return document.querySelector('#inner .c.cur').textContent;
    });
    let target = await typeToAccent();
    await key(target.normalize('NFD')[0]);
    check('A plain vowel for an accented one waits instead of failing', (await a.locator('#inner .c.hold').count()) === 1 && (await a.locator('#inner .c.bad').count()) === 0 && await a.isVisible('#accentHelp'));
    await key(target);
    check('The accent right after is accepted without an error', (await a.locator('#inner .c.hold, #inner .c.bad, #inner .c.fix').count()) === 0 && (await a.textContent('#sAcc')) === '100%');
    // Keyboards that cannot type accents: accents become optional
    target = await typeToAccent();
    await key(target.normalize('NFD')[0]);
    await a.click('#accentLoose');
    check('"Aceptar vocales sin tilde" accepts the waiting vowel', (await a.locator('#inner .c.hold, #inner .c.bad').count()) === 0 && await a.getAttribute('#accMode [data-v="loose"]', 'aria-pressed') === 'true');
    target = await typeToAccent();
    await key(target.normalize('NFD')[0]);
    check('With optional accents a plain vowel counts', (await a.locator('#inner .c.hold, #inner .c.bad').count()) === 0);
    await a.click('#accMode [data-v="strict"]');
    await a.evaluate(() => document.getElementById('cap').blur());
    await a.waitForSelector('#veil', { state: 'visible', timeout: 2000 }).catch(() => {});
    check('Losing focus shows how to continue', await a.isVisible('#veil'));
    await a.click('#veil');
    check('Tapping the text takes the keyboard back', await a.evaluate(() => document.activeElement.id === 'cap'));
    await a.keyboard.press('Escape');

    // Speed measurements by typing method
    await a.click('.mc:nth-child(3) .btn');
    check('Measurements hide the on-screen keyboard', await a.isHidden('#guide') && (await a.textContent('#lName')) === 'A ciegas');
    await typeText(a); await a.waitForSelector('#result:not([hidden])');
    check('The result names the method', (await a.textContent('#result h3')).includes('a ciegas'));
    check('Finishing is a practice_completed event with words per minute and accuracy', await a.evaluate(() => window.tnEvents.some(([e, p]) => e === 'practice_completed' && p.kind === 'medicion' && p.method === 'ciegas' && p.wpm >= 0 && p.accuracy >= 0)));
    check('The result shows who types like you', await a.isVisible('.house-result .typist-art') && (await a.textContent('.house-copy')).includes('mediana'));
    check('Measurements are not limited without payments configured', await a.isHidden('#planNote'));
    await a.waitForFunction(() => document.querySelector('#rankLine')?.textContent);
    check('Impossible speeds stay out of the ranking', (await a.textContent('#rankLine')).includes('no entra al ranking'));
    await a.waitForTimeout(300); await a.click('#rHome');
    await a.click('.mc:nth-child(1) .btn'); await typeText(a); await a.waitForSelector('#result:not([hidden])');
    await a.waitForTimeout(300); await a.click('#rHome');
    check('The chart plots each measurement', (await a.locator('#chartSvg circle.dot').count()) === 2);
    check('Blind and looking speeds are compared', (await a.textContent('#insight')).includes('mirando el teclado'));
    check('The progress ranking lists the user', (await a.textContent('#rankList li.me')).includes('ana'));
    await a.click('#rankView [data-v="speed"]');
    check('Nobody is in the speed ranking with impossible speeds', (await a.locator('#rankList li:not(.rival)').count()) === 0);
    check('The rivales del dojo are in the ranking, marked as bots', (await a.locator('#rankList li.rival').count()) === 10
      && (await a.textContent('#rankList li.rival')).includes('🤖 rival del dojo') && (await a.textContent('#rankNote')).includes('bots de práctica, no personas'));
    // A real speed: a slow measurement that ends by time
    await a.click('.mc:nth-child(2) .btn');
    await a.evaluate(() => { const t = [...document.querySelectorAll('#inner .c')].map(s => s.textContent).join('').slice(0, 40); for (const key of t) document.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true })); });
    await a.evaluate(() => { const now = performance.now.bind(performance); performance.now = () => now() + 61000; });
    await a.waitForFunction(() => /estás #\d+ de 11 /.test(document.querySelector('#rankLine')?.textContent));
    check('The result gives the place in the speed ranking', (await a.textContent('.house-copy h4')).length > 0);
    await a.evaluate(() => { delete performance.now; });
    await a.click('#rHome'); await a.click('#rankView [data-v="speed"]');
    check('The speed ranking lists the user', (await a.textContent('#rankList li.me')).includes('ppm'));
    await a.click('#rankView [data-v="progress"]');
    await a.click('#acctBtn');
    await a.waitForFunction(() => document.querySelectorAll('#hist tbody tr').length === 4);
    check('Lessons and measurements appear in the history', (await a.textContent('#hist tbody')).includes('Lección 1') && (await a.textContent('#hist tbody')).includes('Medición a ciegas'));
    await a.click('#acctClose');

    // Interview training: abstract figures, same design as the lessons
    await a.click('#cogCta');
    check('The header CTA takes you to Ninja mental, on the same page', await a.isVisible('#cog') && await a.isVisible('#home') && a.url().endsWith('#ninja'));
    const cogLevels = await a.$$eval('#cogPath .evo-card b', els => els.map(e => e.textContent));
    check('Each training level has its own typist', cogLevels.join() === 'Nivel chimpancé,Nivel bebé,Nivel niño,Nivel ninja del mate,Nivel intelectual,Nivel premio Nobel');
    check('There are 15 sessions and the mock test', await a.locator('#cogPath .lc').count() === 16);
    await a.click('#cogContinue');
    check('A session starts with a series of figures', await a.isVisible('#quiz') && (await a.textContent('#qPrompt')).includes('sigue') && await a.locator('#qFig .fig').count() === 5 && await a.locator('#qOpts .opt').count() === 4);
    for (let i = 0; i < 6; i++) {
      await a.keyboard.press(String(1 + (i % 4)));
      if (!i) check('Each answer explains the rule', await a.isVisible('#qFeedback') && /^(✓|✗)/.test(await a.textContent('#qExplain')) && await a.locator('#qOpts .opt.right').count() === 1);
      await a.keyboard.press('Enter');
    }
    await a.waitForSelector('#qResult:not([hidden])');
    check('The session result shows stars and the level typist', await a.locator('#qResult .bigstars').count() === 1 && await a.locator('#qResult .result-evo .typist-art').count() === 1);
    await a.click('#qrHome');
    check('The session is saved in the path', (await a.textContent('#cogPath .lc >> nth=0')).includes('Mejor:'));
    await a.click('#cogPath .group:nth-child(2) .lc >> nth=1');
    check('Matrices show a 3×3 grid with a blank', await a.locator('#qFig .q-grid .fig').count() === 8 && await a.locator('#qFig .q-blank').count() === 1);
    await a.keyboard.press('Escape');
    await a.click('#cogPath .group:nth-child(2) .lc >> nth=2');
    check('The odd one out shows five figures to choose from', await a.isHidden('#qFig') && await a.locator('#qOpts .opt').count() === 5);
    await a.keyboard.press('Escape');
    await a.click('#simBtn');
    check('The mock test has 11 questions in 11 minutes', (await a.textContent('#qNum')) === '1/11' && (await a.textContent('#qTime')).startsWith('11:') || (await a.textContent('#qTime')).startsWith('10:5'));
    for (let i = 0; i < 11; i++) await a.keyboard.press('b');
    await a.waitForSelector('#qResult:not([hidden])');
    check('The mock test says who you solve like', (await a.textContent('#qResult .house-copy h4')).length > 0 && await a.isVisible('#qResult .typist-art'));
    await a.click('#qrHome');
    check('The best mock test is shown', (await a.textContent('#cBest')).endsWith('%'));
    // 5-minute run: figures, numbers and English in turn, harder with every 3 right answers, then score and IQ
    await a.click('#maxBtn');
    check('The 5-minute run first explains how it works', await a.isVisible('#qIntro') && await a.isHidden('#qPlay') && (await a.textContent('#qTime')) === '5:00');
    await a.waitForTimeout(1200);
    check('The clock waits for "Empezar"', (await a.textContent('#qTime')) === '5:00');
    const started = a.waitForResponse(r => r.url().endsWith('/api/ninja'));
    await a.keyboard.press('Enter');
    const first = await (await started).json();
    check('The server sends the question without its answer', first.id && first.q.options.length && !('answer' in first.q) && !('explain' in first.q));
    await a.waitForSelector('#qFig .fig');
    check('The 5-minute run starts with a series and a way to finish', await a.isVisible('#qFig .fig') && await a.isVisible('#qEnd'));
    for (let i = 0; i < 5; i++) { await a.keyboard.press(String(1 + (i === 4 ? (srvQ.answer + 1) % srvQ.options.length : srvQ.answer))); await a.waitForTimeout(1300); }
    check('The run counts answers and points as it goes', (await a.textContent('#qNum')) === '5' && (await a.textContent('#qOk')) !== '0' && (await a.textContent('#qNumLbl')) === 'respondidas');
    check('Every 3 right answers the difficulty goes up', (await a.textContent('#qGroup')).includes('dificultad 2 de 5'));
    check('The run mixes figures, numbers and English', srvQ.kind === 'conectores' && await a.isVisible('#qFig .q-gap'));
    check('Each answer says what happened', (await a.textContent('#qFlash')).startsWith('✗ Era la'));
    await a.evaluate(() => { const now = performance.now.bind(performance); performance.now = () => now() + 301000; });
    await a.waitForSelector('#qResult:not([hidden]) .iq');
    check('The run ends with a score and a playful IQ', /^IQ \d+$/.test(await a.textContent('#qResult .iq')) && (await a.textContent('#qResult .nums')).includes('efectividad') && (await a.textContent('#qResult')).includes('no un test de IQ real'));
    check('The server computes the score: 4 right answers at levels 1, 1, 1 and 2, 80% right', (await a.textContent('#qResult .nums b')) === '4' && !(await a.isVisible('.flag-note')));
    await a.waitForFunction(() => document.querySelector('#ninjaRankLine')?.textContent.includes('#1'));
    check('The run gives the place in the ninja ranking', true);
    await a.evaluate(() => { delete performance.now; });
    // Finishing early and leaving halfway also give the result
    await a.click('#qrAgain'); await a.click('#qGo'); await a.waitForSelector('#qFig .fig');
    await a.keyboard.press(String(1 + srvQ.answer)); await a.waitForTimeout(400);
    await a.click('#qEnd');
    await a.waitForSelector('#qResult .iq');
    check('"Terminar ahora" shows the result right away', (await a.textContent('#qResult .nums')).includes('1/1'));
    await a.click('#qrAgain'); await a.click('#qGo'); await a.waitForSelector('#qFig .fig');
    await a.keyboard.press('1'); await a.waitForTimeout(800);
    await a.click('#qBack');
    await a.waitForSelector('#qResult .iq');
    check('Leaving the run halfway shows the result instead of losing it', await a.isVisible('#qResult .iq'));
    await a.click('#qrChallenge');
    const nwa = decodeURIComponent(await a.getAttribute('#chWhatsapp', 'href'));
    check('A run can be sent as a challenge, pointing to the run kept by the server', nwa.includes('Ninja mental') && /reto=[\w-]{22}/.test(nwa) && !/ninja=\d/.test(nwa) && nwa.includes('#ninja'));
    await a.click('#chClose'); await a.click('#qrHome');
    check('The ninja ranking in the section lists the user', (await a.textContent('#ninjaRank li.me')).includes('ana') && (await a.textContent('#maxBest')).includes('IQ 100 · 4 puntos'));
    await a.click('#maxInvite');
    const ninjaLink = /http:\/\/127\S+/.exec(decodeURIComponent(await a.getAttribute('#chWhatsapp', 'href')))[0];
    check('The challenge of the best mark says its score', (await a.textContent('#chLead')).includes('4 puntos'));
    await a.click('#chClose');
    // Cheating: a score sent by the browser, clicks made by a script and a pointer that jumps to the answers
    const forged = await a.evaluate(async () => (await fetch('/api/data', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + localStorage.getItem('teclado-ciego-token') },
      body: JSON.stringify({ type: 'progress', progress: { lessons: {}, ninja: { best: { score: 299, iq: 160, ok: 60, n: 60, date: Date.now() }, runs: [] } } }) })).ok);
    const ninjaBoard = async () => (await (await fetch(SITE + '/api/ranking')).json()).ninja.top.filter(r => !r.rival);
    check('A score reported by the browser is ignored', forged && (await ninjaBoard())[0].score === 4);
    const scriptRun = async answer => {
      await a.click('#maxBtn'); await a.click('#qGo'); await a.waitForSelector('#qFig .fig');
      for (let i = 0; i < 4; i++) { await answer(i); await a.waitForFunction(i => document.querySelector('#qNum').textContent === String(i + 1), i, { timeout: 5000 }); await a.waitForTimeout(1200); }
      await a.click('#qEnd'); await a.waitForSelector('#qResult .iq');
    };
    await scriptRun(() => a.evaluate(n => document.querySelectorAll('#qOpts .opt')[n].click(), srvQ.answer));
    check('Clicks made by a script: the run does not count', (await a.textContent('.flag-note')).includes('Esta partida no cuenta para el ranking') && (await a.textContent('.flag-note')).includes('programa'));
    check('A flagged run can only invite, not challenge', (await a.textContent('#qrChallenge')) === 'Invitar a un amigo');
    await a.click('#qrHome');
    const jumpTo = async (i, steps) => {
      const opts = a.locator('#qOpts .opt'), opt = opts.nth(i % 2 ? (await opts.count()) - 1 : 0);
      await opt.scrollIntoViewIfNeeded(); await a.waitForTimeout(500);
      const box = await opt.boundingBox();
      if (steps) await a.mouse.move(box.x + 5, box.y + 5, { steps });
      await a.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
    };
    await scriptRun(i => jumpTo(i, 0));
    check('A pointer that jumps straight to the answers: the run does not count', (await a.textContent('.flag-note')).includes('saltaba'));
    check('Flagged runs stay out of the ranking', (await ninjaBoard())[0].score === 4);
    await a.click('#qrHome');
    await scriptRun(i => jumpTo(i, 12));
    check('A person moving the mouse: the run counts', await a.isHidden('.flag-note') && (await a.textContent('#qrChallenge')) === 'Desafiar a un amigo');
    await a.click('#qrHome');
    // The weak signs need to come together: an even rhythm alone, or a near-perfect run alone, is not enough
    const sig = { input: 'key', trusted: true, focus: true, moves: 0, jump: 0 };
    const even = Array.from({ length: 12 }, (_, i) => ({ ...sig, k: 'serie', d: 5, right: true, ms: 6000 + (i % 2) * 300 }));
    const uneven = even.map((x, i) => ({ ...x, ms: [4000, 15000, 7000, 26000][i % 4] }));
    check('An even rhythm and a perfect run together are flagged', suspicious(even, 1, 5).flagged && suspicious(even, 1, 5).reasons.length === 2);
    check('A perfect run with a human rhythm is not', !suspicious(uneven, 1, 5).flagged);
    check('An even rhythm alone is not', !suspicious(even, 0.6, 3).flagged);
    // Numerical reasoning and English tracks, with a technique (tip) in every question
    await a.evaluate(() => { for (const G of [Numeric, English]) for (const k of Object.keys(G.make)) { const f = G.make[k]; G.make[k] = (d, u) => { const q = f(d, u); (window.qlog ||= []).push(q); return q; }; } });
    await a.click('#cogTracks [data-v="num"]');
    check('Ninja mental has a numerical reasoning track', (await a.textContent('#cogTitle')).includes('Razonamiento numérico') && (await a.textContent('#cogKinds')).includes('Técnicas') && await a.locator('#cogPath .lc').count() === 16);
    await a.evaluate(() => { window.qlog = []; });
    await a.click('#cogContinue');
    check('A numerical session shows a table, a tip and text options', await a.isVisible('#qFig .q-table') && await a.isVisible('#qTip') && (await a.textContent('#qTip')).includes('Técnica') && await a.locator('#qOpts .opt-txt').count() === 4);
    await a.keyboard.press(String(1 + await a.evaluate(() => qlog[0].answer)));
    check('The numerical answer shows the worked solution', (await a.textContent('#qExplain')).startsWith('✓') && /[0-9]/.test(await a.textContent('#qExplain')));
    await a.keyboard.press('Escape');
    await a.click('#cogPath .group:nth-child(1) .lc >> nth=1');
    check('Chart questions draw a bar chart', await a.locator('#qFig svg.q-chart rect.bar').count() === 8);
    await a.keyboard.press('Escape');
    await a.click('#cogTracks [data-v="eng"]');
    check('Ninja mental has an English track', (await a.textContent('#cogTitle')).includes('Inglés para el trabajo'));
    await a.evaluate(() => { window.qlog = []; });
    await a.click('#cogContinue');
    check('Reading questions are True / False / Cannot say', (await a.textContent('#qOpts')).includes('Cannot say') && await a.locator('#qOpts .opt').count() === 3 && await a.isVisible('#qFig .q-stmt'));
    const wrongPick = await a.evaluate(() => (qlog[0].answer + 1) % 3);
    await a.keyboard.press(String(wrongPick + 1));
    check('A wrong answer explains why and gives a technique for next time', (await a.textContent('#qExplain')).startsWith('✗') && (await a.textContent('#qExplain')).includes('Para la próxima'));
    await a.keyboard.press('Escape');
    await a.click('#cogPath .group:nth-child(1) .lc >> nth=2');
    check('Ordering sessions have 5 questions with numbered sentences', (await a.textContent('#qNum')) === '1/5' && await a.locator('#qFig .q-sent li').count() === 4);
    await a.keyboard.press('Escape');
    await a.click('#simBtn');
    check('The English mock test has 12 questions and no tips', (await a.textContent('#qNum')) === '1/12' && await a.isHidden('#qTip'));
    for (let i = 0; i < 12; i++) await a.keyboard.press('1');
    await a.waitForSelector('#qResult:not([hidden])');
    check('The mock test review gives the technique of each mistake', (await a.textContent('#qResult h3')).includes('Inglés') && (await a.locator('#qResult .rv').count() === 0 || await a.locator('#qResult .rv-tip').count() > 0));
    await a.click('#qrHome');
    check('Each track keeps its own mock test', (await a.textContent('#cBest')).endsWith('%') && (await a.textContent('#cogTracks [data-v="eng"] small')).includes('/15'));
    // Logic track (logic.js) and the company mock test
    await a.click('#cogTracks [data-v="log"]');
    check('Ninja mental has a logic track with 15 sessions', (await a.textContent('#cogTitle')).includes('Lógica y series') && (await a.textContent('#cogTracks [data-v="log"] small')).includes('/15'));
    check('Every logic puzzle has one right answer among distinct options, at every level', await a.evaluate(() => Logic.KINDS.every(k => [1, 2, 3, 4, 5].every(d => Array.from({ length: 60 }, () => Logic.make[k](d))
      .every(q => q.answer >= 0 && q.answer < q.options.length && new Set(q.options).size === q.options.length && q.explain && q.tip)))));
    await a.evaluate(() => { window.qlog = []; for (const k of Object.keys(Logic.make)) { const f = Logic.make[k]; Logic.make[k] = (d, u) => { const q = f(d, u); qlog.push(q); return q; }; } });
    await a.click('#cogContinue');
    check('Number series show the series and four options', await a.isVisible('#qFig .q-series') && await a.locator('#qOpts .opt').count() === 4);
    await a.keyboard.press(String(1 + await a.evaluate(() => qlog[0].answer)));
    check('A right series answer explains the rule', (await a.textContent('#qExplain')).startsWith('✓') && (await a.textContent('#qExplain')).includes('sigue'));
    await a.keyboard.press('Escape');
    await a.click('#cogPath .group:nth-child(1) .lc >> nth=2');
    check('Syllogisms show two premises and True / False / Can\'t say', await a.locator('#qFig .q-clues li').count() === 2 && (await a.textContent('#qOpts')).includes('No se puede saber') && await a.locator('#qOpts .opt').count() === 3);
    await a.keyboard.press('Escape');
    check('The logic track offers the company mock test', (await a.textContent('[data-company="meli"]')).includes('Mercado Libre'));
    await a.click('[data-company="meli"]');
    check('The Mercado Libre-style mock test has 40 questions in 30 minutes and no tips', (await a.textContent('#qNum')) === '1/40' && (await a.textContent('#qGroup')).includes('40 preguntas en 30 minutos') && await a.isHidden('#qTip'));
    await a.keyboard.press('Escape');
    await a.click('#cogTracks [data-v="fig"]');
    await a.click('.main-nav a[href="#learning"]');
    check('Lessons are one click away', await a.isVisible('#home') && !a.url().includes('#ninja'));
    await a.click('#rankView [data-v="ninja"]');
    check('The main ranking has a Ninja tab', (await a.textContent('#rankList li.me')).includes('IQ'));
    await a.click('#rankView [data-v="cog"]');
    check('The Ninja mental progress ranking lists the user or says how to join', (await a.locator('#rankList li.me').count()) ? (await a.textContent('#rankList li.me')).includes('sesiones') : /Aprobá una sesión|Estrenalo/.test(await a.textContent('#rankNote')));
    await a.click('#rankView [data-v="general"]');
    check('The general ranking adds everything up', (await a.textContent('#rankList li.me')).includes('pts'));
    await a.click('#rankView [data-v="progress"]');

    // Challenge a friend: the link carries the score
    await a.click('#inviteBtn');
    const wa = await a.getAttribute('#chWhatsapp', 'href');
    check('The WhatsApp invitation carries a challenge link', wa.startsWith('https://wa.me/?text=') && decodeURIComponent(wa).includes('de=ana') && decodeURIComponent(wa).includes('ppm='));
    check('The email invitation is ready too', (await a.getAttribute('#chMail', 'href')).startsWith('mailto:?subject='));
    await a.fill('#chEmail', 'amigo@example.com');
    check('The friend email goes into the email', (await a.getAttribute('#chMail', 'href')).startsWith('mailto:amigo@example.com?'));
    const link = decodeURIComponent(wa).match(/http:\/\/127\S+/)[0];
    await a.click('#chClose');
    const f = await (await browser.newContext()).newPage(); f.on('pageerror', e => errors.push(e.message));
    await f.goto(link.replace(/ppm=\d+/, 'ppm=3'));
    check('A friend opening the link sees the challenge', (await f.textContent('#challengeTitle')).includes('ana te desafía: 3 palabras'));
    check('The challenge link is cleaned from the address bar', !f.url().includes('de='));
    await f.click('#challengeAccept');
    await f.evaluate(() => { const t = [...document.querySelectorAll('#inner .c')].map(s => s.textContent).join('').slice(0, 40); for (const key of t) document.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true })); });
    await f.evaluate(() => { const now = performance.now.bind(performance); performance.now = () => now() + 61000; });
    await f.waitForSelector('.challenge-result');
    check('The friend learns who won', (await f.textContent('.challenge-result')).includes('ganaste a ana'));
    await f.click('#rChallenge');
    check('The friend can send the rematch', decodeURIComponent(await f.getAttribute('#chWhatsapp', 'href')).includes('¿Me ganás?'));

    // Second computer: log in and find the progress
    const b = await (await browser.newContext()).newPage(); b.on('pageerror', e => errors.push(e.message));
    await b.goto(SITE);
    await b.click('#acctBtn'); await b.fill('#user', 'ana'); await b.fill('#pass', 'otra-clave'); await b.click('#authSubmit');
    await b.waitForFunction(() => document.querySelector('#authErr').textContent);
    check('Wrong passwords are rejected', (await b.textContent('#authErr')).includes('incorrectos'));
    await b.waitForFunction(() => document.querySelectorAll('#rankList li:not(.rival)').length === 1);
    check('Guests see the ranking of everyone', (await b.textContent('#rankList')).includes('ana') && (await b.textContent('#rankNote')).includes('Entrá'));
    // A friend opens a Ninja mental challenge
    const nf = await (await browser.newContext()).newPage(); nf.on('pageerror', e => errors.push(e.message));
    await nf.goto(SITE + '/?de=pepe&ninja=300#ninja');
    check('An old link with a score in it is only an invitation', (await nf.textContent('#challengeTitle')) === 'pepe te invita a Ninja mental');
    await nf.goto(ninjaLink);
    await nf.waitForFunction(() => document.querySelector('#challengeTitle').textContent.includes('verificados'));
    check('A ninja challenge opens Ninja mental with the banner and the score from the server', await nf.isVisible('#cog') && (await nf.textContent('#challengeTitle')).includes('ana te desafía en Ninja mental: IQ') && (await nf.textContent('#challengeTitle')).includes('(4 puntos'));
    await nf.click('#challengeAccept');
    check('Accepting starts the 5-minute run', (await nf.textContent('#qName')) === 'Desafío de 5 minutos');
    await nf.click('#qGo'); await nf.waitForSelector('#qFig .fig');
    await nf.evaluate(() => { const now = performance.now.bind(performance); performance.now = () => now() + 301000; });
    await nf.waitForSelector('#qResult:not([hidden]) .challenge-result');
    check('The friend learns who won the ninja challenge', (await nf.textContent('.challenge-result')).includes('ana'));
    await b.fill('#pass', 'secreto1'); await b.click('#authSubmit');
    await b.waitForFunction(() => document.querySelector('#hStars').textContent !== '0/78');
    check('Progress follows the account to another browser', (await b.textContent('.lc')).includes('Mejor:'));
    await b.goto(SITE + '/#ninja'); await b.waitForSelector('#acctBtn .nm');
    await b.waitForFunction(() => document.querySelector('#cogPath .lc')?.textContent.includes('Mejor:'));
    check('The interview training follows the account too', (await b.textContent('#cBest')).endsWith('%'));
    await b.click('#homeBtn');
    await b.click('#evoView [data-v="table"]');
    check('Measurements follow the account too', (await b.locator('#evoTable tbody tr').count()) === 3);
    await b.reload(); await b.waitForSelector('#acctBtn .nm');
    check('The session survives a reload', (await b.textContent('#acctBtn .nm')) === 'ana');
    // The name shown in the ranking can change; the username to log in stays
    await b.click('#acctBtn');
    check('The account shows the username to log in', (await b.textContent('#aliasHint')).includes('ana'));
    await b.fill('#alias', '  Ana   Ninja '); await b.click('#aliasSave');
    await b.waitForFunction(() => document.querySelector('#acctBtn .nm').textContent === 'Ana Ninja');
    check('The new name is in the header and the greeting', (await b.textContent('#acctTitle')) === 'Hola, Ana Ninja');
    await b.click('#acctClose');
    await b.waitForFunction(() => document.querySelector('#rankList li.me')?.textContent.includes('Ana Ninja'));
    check('The ranking shows the new name', true);
    const ranking = await (await fetch(SITE + '/api/ranking')).json();
    check('The API marks the rivals and does not count them as people', ranking.speed.total === 1 && ranking.speed.rivals === 10
      && ranking.speed.top.filter(r => r.rival).length === 10 && ranking.speed.top.every(r => r.rival ? r.name.startsWith('rival:') : r.display === 'Ana Ninja'));
    const call = async (payload, token) => { const r = await fetch(SITE + '/api/auth', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: JSON.stringify(payload) }); return { status: r.status, ...(await r.json()) }; };
    const pepe = await call({ action: 'register', username: 'pepe', password: 'secreto1' });
    check('Nobody else can take a name in use, with other accents, case or spaces', (await call({ action: 'display', display: 'ána ninja' }, pepe.token)).status === 409);
    check('Nobody can show someone else\'s username', (await call({ action: 'display', display: 'ANA' }, pepe.token)).status === 409);
    check('Nobody can pass for a rival', (await call({ action: 'display', display: 'Sensei Mei' }, pepe.token)).status === 409);
    check('Names with odd characters are rejected', (await call({ action: 'display', display: '<b>yo</b>' }, pepe.token)).status === 400);
    check('A free name is taken', (await call({ action: 'display', display: 'Pepe Grillo' }, pepe.token)).user?.display === 'Pepe Grillo');
    check('Changing the name needs a session', (await call({ action: 'display', display: 'Otro' })).status === 401);
    check('The username still logs in', (await call({ action: 'login', username: 'ana', password: 'secreto1' })).user?.display === 'Ana Ninja');
    await b.reload(); await b.waitForSelector('#acctBtn .nm');
    check('The new name survives a reload', (await b.textContent('#acctBtn .nm')) === 'Ana Ninja');
    await b.click('#acctBtn'); await b.fill('#alias', ''); await b.click('#aliasSave');
    await b.waitForFunction(() => document.querySelector('#acctBtn .nm').textContent === 'ana');
    check('An empty name goes back to the username and frees the old one', (await call({ action: 'display', display: 'Ana Ninja' }, pepe.token)).user?.display === 'Ana Ninja');
    await b.click('#acctClose');
    await b.click('#acctBtn'); await b.click('#logout');
    await b.waitForFunction(() => document.querySelector('#acctBtn').textContent.trim() === 'Entrar');
    check('Logging out clears this browser', (await b.textContent('#hStars')) === '0/78');

    // /profesional: the company and test-type page, and its links into the app
    const pro = await browser.newPage(); pro.on('pageerror', e => errors.push(e.message));
    await pro.goto(SITE + '/profesional');
    check('/profesional shows the companies and links to their practice', (await pro.textContent('h1')).includes('tests de selección') && await pro.locator('.co').count() >= 5
      && await pro.locator('a[href="/?simulacro=meli"]').count() >= 2 && (await pro.textContent('main')).includes('no está afiliado'));
    await pro.goto(SITE + '/?pista=log');
    check('A link with ?pista opens that track', (await pro.textContent('#cogTitle')).includes('Lógica') && pro.url().includes('#ninja'));
    await pro.goto(SITE + '/?pista=toString&simulacro=constructor'); await pro.waitForTimeout(200);
    check('Unknown ?pista and ?simulacro values are ignored', await pro.isVisible('#home') && errors.length === 0);
    await pro.goto(SITE + '/?simulacro=meli');
    check('A link with ?simulacro starts the company mock test', (await pro.textContent('#qNum')) === '1/40' && await pro.isVisible('#qOpts .opt'));

    check('No uncaught browser errors', errors.length === 0);
  } finally {
    await browser.close(); server.close();
    if (errors.length) console.error(errors);
  }
})().catch(err => { console.error(err); process.exit(1); });
